spring.application.name=springBoot
spring.datasource.url=jdbc:postgresql://localhost:5432/Manoj
spring.datasource.username=postgres
spring.datasource.password=Test@123
spring.datasource.driver.class.name=org.postgresql.Driver