spring.application.name=ecoomerce_Sring_boot_P1

spring.datasource.url=jdbc:postgresql://localhost:5432/Java
spring.datasource.username=postgres
spring.datasource.password=Manoj@205
spring.datasource.driver.class.name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update